"""Initial migration

Revision ID: ebe82283b901
Revises: 
Create Date: 2025-05-02 10:58:23.893694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe82283b901'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('club_type', sa.String(), nullable=True),
    sa.Column('club_name', sa.String(), nullable=True),
    sa.Column('club_brand', sa.String(), nullable=True),
    sa.Column('club_model', sa.String(), nullable=True),
    sa.Column('club_loft', sa.String(), nullable=True),
    sa.Column('club_flex', sa.String(), nullable=True),
    sa.Column('club_length', sa.String(), nullable=True),
    sa.Column('club_lie', sa.String(), nullable=True),
    sa.Column('club_swing_weight', sa.String(), nullable=True),
    sa.Column('club_shaft', sa.String(), nullable=True),
    sa.Column('club_grip', sa.String(), nullable=True),
    sa.Column('club_price', sa.String(), nullable=True),
    sa.Column('club_image_url', sa.String(), nullable=True),
    sa.Column('club_description', sa.Text(), nullable=True),
    sa.Column('club_features', sa.JSON(), nullable=True),
    sa.Column('club_specs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ### 